import type { Metadata } from "next";
import "./globals.css";
import 'material-icons/iconfont/material-icons.css'
import ThemeRegistry from "@/app/theme/ThemeRegistry";

export const metadata: Metadata = {
  title: "Posts-Placeholder",
  description: "Generated by Eduardo Borraz",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
