import type { Metadata } from "next";
import HomeStyles from "@/app/(home)/page.module.css";
import "material-icons/iconfont/material-icons.css";
import ThemeRegistry from "@/theme/ThemeRegistry";
import "../../app/globals.css";

export const metadata: Metadata = {
  title: "Posts-Placeholder",
  description: "Generated by Eduardo Borraz",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <div className={HomeStyles.main}>{children}</div>
        </ThemeRegistry>
      </body>
    </html>
  );
}
